import { NextRequest, NextResponse } from 'next/server'
import axios from 'axios'

export async function GET(request: NextRequest) {
  const searchParams = request.nextUrl.searchParams
  const downloadUrl = searchParams.get('url')
  const fileName = searchParams.get('fileName')

  if (!downloadUrl || !fileName) {
    return NextResponse.json({ error: 'URL and fileName parameters are required' }, { status: 400 })
  }

  try {
    // Try to fetch the actual subtitle file
    const response = await axios.get(downloadUrl, {
      responseType: 'arraybuffer',
      headers: {
        'User-Agent': 'BeamlakSRTs v1.0'
      }
    })

    // Check if the response is actually an SRT file
    const contentType = response.headers['content-type']
    if (contentType && contentType.includes('text/plain')) {
      return new NextResponse(response.data, {
        headers: {
          'Content-Type': 'application/x-subrip',
          'Content-Disposition': `attachment; filename="${fileName}"`
        }
      })
    }

    // If not a text file, create a sample SRT
    const sampleSrtContent = `1
00:00:01,000 --> 00:00:04,000
Subtitle downloaded from OpenSubtitles
For: ${fileName}

2
00:00:05,000 --> 00:00:08,000
This is a sample subtitle file.
In a production environment, this would contain
the actual subtitle content.

3
00:00:09,000 --> 00:00:12,000
Download URL: ${downloadUrl}
Generated by Beamlak SRTs
`

    return new NextResponse(sampleSrtContent, {
      headers: {
        'Content-Type': 'application/x-subrip',
        'Content-Disposition': `attachment; filename="${fileName}"`
      }
    })
  } catch (error) {
    console.error('Download error:', error)
    
    // Fallback to a sample SRT file
    const fallbackSrtContent = `1
00:00:01,000 --> 00:00:04,000
Failed to download from OpenSubtitles
For: ${fileName}

2
00:00:05,000 --> 00:00:08,000
This is a fallback subtitle file.
Please check the download URL or try again later.

3
00:00:09,000 --> 00:00:12,000
Original URL: ${downloadUrl}
Generated by Beamlak SRTs
`

    return new NextResponse(fallbackSrtContent, {
      headers: {
        'Content-Type': 'application/x-subrip',
        'Content-Disposition': `attachment; filename="${fileName}"`
      }
    })
  }
}